# Generated by Django 3.0.2 on 2020-03-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahooleague',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='League Name'),
        ),
    ]
