# Generated by Django 3.0.2 on 2020-06-29 23:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=4, verbose_name='Year Number')),
            ],
            options={
                'ordering': ('-created_timestamp',),
                'abstract': False,
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='current_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current Week'),
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='draft_status',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Draft Status'),
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='league_type',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='League Type'),
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='num_teams',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Teams'),
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='playoff_start_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Playoff Start Week'),
        ),
        migrations.AlterField(
            model_name='yahooleague',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='League Name'),
        ),
        migrations.AlterField(
            model_name='yahooleague',
            name='remote_id',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Remote Object Id'),
        ),
        migrations.CreateModel(
            name='YahooMultiYearLeague',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('leagues', models.ManyToManyField(to='leagues.YahooLeague', verbose_name='Leagues')),
            ],
            options={
                'ordering': ('-created_timestamp',),
                'abstract': False,
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='YahooLeagueWeeks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('remote_id', models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Remote Object Id')),
                ('week_number', models.IntegerField(blank=True, null=True, verbose_name='Week Number')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_current_week', models.BooleanField(default=False, verbose_name='Is Current Week')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='leagues.YahooLeague', verbose_name='Yahoo Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YahooGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('remote_id', models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Remote Object Id')),
                ('code', models.CharField(default='mlb', max_length=128, verbose_name='Game Code')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.Year', verbose_name='Year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='leagues.YahooGame', verbose_name='Yahoo Game'),
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='leagues.Year', verbose_name='Year'),
        ),
    ]
