# Generated by Django 3.0.2 on 2020-03-14 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20200314_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('remote_id', models.CharField(max_length=1024, unique=True, verbose_name='Remote Object Id')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='League Name')),
                ('year', models.IntegerField(verbose_name='Fantasy Game year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
