# Generated by Django 3.0.2 on 2020-03-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_yahoogame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahoogame',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Game Code'),
        ),
        migrations.AlterField(
            model_name='yahoogame',
            name='remote_id',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Remote Object Id'),
        ),
        migrations.AlterField(
            model_name='yahooleague',
            name='remote_id',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Remote Object Id'),
        ),
    ]
