# Generated by Django 3.0.3 on 2020-06-30 23:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_remove_yahooleague_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooOauthCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('consumer_key', models.CharField(max_length=1024, verbose_name='Consumer Key')),
                ('consumer_secret', models.CharField(max_length=1024, verbose_name='Consumer Secret')),
                ('access_token', models.CharField(max_length=1024, verbose_name='Access Token')),
                ('refresh_token', models.CharField(max_length=1024, verbose_name='Refresh Token')),
                ('token_time', models.FloatField(verbose_name='Refresh Token')),
                ('token_type', models.CharField(default='bearer', max_length=1024, verbose_name='Refresh Token')),
            ],
            options={
                'ordering': ('-created_timestamp',),
                'abstract': False,
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.AlterModelOptions(
            name='yahoogame',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ('-created_timestamp',)},
        ),
        migrations.RemoveField(
            model_name='yahoogame',
            name='remote_id',
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='yahoo_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues', to='leagues.YahooOauthCredentials', verbose_name='Oauth Credentials'),
        ),
    ]
