# Generated by Django 3.0.2 on 2020-03-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20200314_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahoogame',
            name='code',
            field=models.CharField(default='mlb', max_length=128, verbose_name='Game Code'),
        ),
    ]
