# Generated by Django 3.0.3 on 2020-07-01 00:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_yahooleague_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahooleague',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Meta'),
        ),
    ]
