# Generated by Django 3.0.2 on 2020-03-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_auto_20200314_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooleague',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='leagues.YahooGame', verbose_name='Yahoo Game'),
            preserve_default=False,
        ),
    ]
