# Generated by Django 3.0.2 on 2020-03-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_yahooleague_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooleague',
            name='current_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current Week'),
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='draft_status',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Draft Status'),
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='league_type',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='League Type'),
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='num_teams',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Teams'),
        ),
        migrations.AddField(
            model_name='yahooleague',
            name='playoff_start_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Playoff Start Week'),
        ),
    ]
