# Generated by Django 3.0.3 on 2020-07-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_auto_20200701_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooleague',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is Visible'),
        ),
        migrations.AlterField(
            model_name='yahoooauthcredentials',
            name='token_time',
            field=models.FloatField(verbose_name='Token Time'),
        ),
        migrations.AlterField(
            model_name='yahoooauthcredentials',
            name='token_type',
            field=models.CharField(default='bearer', max_length=1024, verbose_name='Token Type'),
        ),
    ]
