# Generated by Django 3.0.2 on 2020-03-21 23:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_auto_20200314_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooLeagueWeeks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('remote_id', models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Remote Object Id')),
                ('week_number', models.IntegerField(blank=True, null=True, verbose_name='Week Number')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
