# Generated by Django 3.0.3 on 2020-07-02 01:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_auto_20200702_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooleague',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Stats'),
        ),
    ]
