# Generated by Django 3.0.2 on 2020-03-22 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_yahooleagueweeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooleagueweeks',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='leagues.YahooLeague', verbose_name='Yahoo Game'),
            preserve_default=False,
        ),
    ]
