# Generated by Django 3.0.3 on 2020-07-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_yahooleague_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooleague',
            name='domain',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Domain'),
        ),
    ]
