# Generated by Django 3.0.2 on 2020-03-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_yahooleagueweeks_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooleagueweeks',
            name='is_current_week',
            field=models.BooleanField(default=False, verbose_name='Is Current Week'),
        ),
    ]
