# Generated by Django 3.0.3 on 2020-07-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_yahoomultiyearleague_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahoomultiyearleague',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
