# Generated by Django 3.0.3 on 2020-07-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_yahoomultiyearleague_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahoooauthcredentials',
            name='access_token',
            field=models.CharField(max_length=8192, verbose_name='Access Token'),
        ),
    ]
