# Generated by Django 3.0.3 on 2021-04-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_rotomultileagues'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotomultileagues',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
