# Generated by Django 3.0.3 on 2021-05-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_rotomultileagues_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotomultileagues',
            name='domain',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Domain'),
        ),
    ]
