# Generated by Django 3.0.3 on 2021-05-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_rotomultileagues_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotomultileagues',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Name'),
        ),
    ]
