# Generated by Django 3.0.2 on 2020-03-14 22:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_auto_20200314_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('remote_id', models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Remote Object Id')),
                ('first_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Team Name')),
                ('last_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Team Name')),
                ('editorial_team_full_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Professional Team Name')),
                ('eligible_positions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Eligible positions')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.YahooTeam', verbose_name='Yahoo Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
