# Generated by Django 3.0.2 on 2020-03-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahooplayer',
            name='remote_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Remote Object Id'),
        ),
    ]
