# Generated by Django 3.0.2 on 2020-06-30 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahooplayerleague',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='players.YahooPlayer', verbose_name='Yahoo Team'),
        ),
    ]
