# Generated by Django 3.0.2 on 2020-05-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20200321_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcstats',
            name='gap',
            field=models.FloatField(blank=True, null=True, verbose_name='Games as Pitcher'),
        ),
        migrations.AddField(
            model_name='baseballavestats',
            name='gap',
            field=models.FloatField(blank=True, null=True, verbose_name='Games as Pitcher'),
        ),
        migrations.AddField(
            model_name='depthchartsstats',
            name='gap',
            field=models.FloatField(blank=True, null=True, verbose_name='Games as Pitcher'),
        ),
        migrations.AddField(
            model_name='steamerstats',
            name='gap',
            field=models.FloatField(blank=True, null=True, verbose_name='Games as Pitcher'),
        ),
        migrations.AddField(
            model_name='thebatstats',
            name='gap',
            field=models.FloatField(blank=True, null=True, verbose_name='Games as Pitcher'),
        ),
        migrations.AddField(
            model_name='zipsstats',
            name='gap',
            field=models.FloatField(blank=True, null=True, verbose_name='Games as Pitcher'),
        ),
    ]
