# Generated by Django 3.0.2 on 2020-03-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_baseballplayer_steamerstats_zipsstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseballplayer',
            name='remote_player_id',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Team Name'),
        ),
    ]
