# Generated by Django 3.0.2 on 2020-03-15 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_baseballplayer_remote_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooplayer',
            name='baseball_player_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.BaseballPlayer'),
        ),
        migrations.AlterField(
            model_name='baseballplayer',
            name='remote_player_id',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Remote Player Id'),
        ),
    ]
