# Generated by Django 3.0.3 on 2020-06-30 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20200630_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahooplayerleague',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='players.BaseballPlayer', verbose_name='Yahoo Team'),
        ),
    ]
