# Generated by Django 3.0.2 on 2020-03-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20200315_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yahooplayer',
            old_name='baseball_player_id',
            new_name='baseball_player',
        ),
    ]
