# Generated by Django 3.0.3 on 2020-07-17 03:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20200717_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseballplayer',
            name='eligible_positions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Eligible positions'),
        ),
    ]
