# Generated by Django 3.0.3 on 2020-07-18 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20200717_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionBaseballPlayer',
            fields=[
                ('baseballplayer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.BaseballPlayer')),
                ('mAVG', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mRBI', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mR', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mHR', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mOBP', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mSLG', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mOPS', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mH', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mSO', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mBB', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mSBCS', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mSV', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mERA', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mWHIP', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mK9', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mBB9', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mKBB', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mIP', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mHLD', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mQS', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('mSVHLD', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('PTS', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('aPOS', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
                ('Dollars', models.FloatField(blank=True, null=True, verbose_name='Games Played')),
            ],
            options={
                'abstract': False,
            },
            bases=('players.baseballplayer', models.Model),
        ),
    ]
