# Generated by Django 3.0.3 on 2020-07-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auctionbaseballplayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuctionBaseballPlayer',
        ),
    ]
