# Generated by Django 3.0.3 on 2020-07-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auctionbaseballplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='Dollars',
            field=models.FloatField(blank=True, null=True, verbose_name='Dollars'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='PTS',
            field=models.FloatField(blank=True, null=True, verbose_name='PTS'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='aPOS',
            field=models.FloatField(blank=True, null=True, verbose_name='aPOS'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mAVG',
            field=models.FloatField(blank=True, null=True, verbose_name='mAVG'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mBB',
            field=models.FloatField(blank=True, null=True, verbose_name='mBB'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mBB9',
            field=models.FloatField(blank=True, null=True, verbose_name='mBB9'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mERA',
            field=models.FloatField(blank=True, null=True, verbose_name='mERA'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mH',
            field=models.FloatField(blank=True, null=True, verbose_name='mH'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mHLD',
            field=models.FloatField(blank=True, null=True, verbose_name='mHLD'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mHR',
            field=models.FloatField(blank=True, null=True, verbose_name='mHR'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mIP',
            field=models.FloatField(blank=True, null=True, verbose_name='mIP'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mK9',
            field=models.FloatField(blank=True, null=True, verbose_name='mK9'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mKBB',
            field=models.FloatField(blank=True, null=True, verbose_name='mKBB'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mOBP',
            field=models.FloatField(blank=True, null=True, verbose_name='mOBP'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mOPS',
            field=models.FloatField(blank=True, null=True, verbose_name='mOPS'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mQS',
            field=models.FloatField(blank=True, null=True, verbose_name='mQS'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mR',
            field=models.FloatField(blank=True, null=True, verbose_name='mR'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mRBI',
            field=models.FloatField(blank=True, null=True, verbose_name='mRBI'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mSBCS',
            field=models.FloatField(blank=True, null=True, verbose_name='mSBCS'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mSLG',
            field=models.FloatField(blank=True, null=True, verbose_name='mSLG'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mSO',
            field=models.FloatField(blank=True, null=True, verbose_name='mSO'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mSV',
            field=models.FloatField(blank=True, null=True, verbose_name='mSV'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mSVHLD',
            field=models.FloatField(blank=True, null=True, verbose_name='mSVHLD'),
        ),
        migrations.AlterField(
            model_name='auctionbaseballplayer',
            name='mWHIP',
            field=models.FloatField(blank=True, null=True, verbose_name='mWHIP'),
        ),
    ]
