# Generated by Django 3.0.3 on 2020-07-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20200718_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcstats',
            name='winp',
            field=models.FloatField(blank=True, null=True, verbose_name='Winning Percentage'),
        ),
        migrations.AddField(
            model_name='baseballavestats',
            name='winp',
            field=models.FloatField(blank=True, null=True, verbose_name='Winning Percentage'),
        ),
        migrations.AddField(
            model_name='depthchartsstats',
            name='winp',
            field=models.FloatField(blank=True, null=True, verbose_name='Winning Percentage'),
        ),
        migrations.AddField(
            model_name='steamerstats',
            name='winp',
            field=models.FloatField(blank=True, null=True, verbose_name='Winning Percentage'),
        ),
        migrations.AddField(
            model_name='thebatstats',
            name='winp',
            field=models.FloatField(blank=True, null=True, verbose_name='Winning Percentage'),
        ),
        migrations.AddField(
            model_name='zipsstats',
            name='winp',
            field=models.FloatField(blank=True, null=True, verbose_name='Winning Percentage'),
        ),
    ]
