# Generated by Django 3.0.3 on 2021-06-05 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('body', models.TextField(max_length=1024, verbose_name='body')),
                ('is_enable', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('start_datetime', models.DateTimeField(null=True, verbose_name='Start Datetime')),
                ('end_datetime', models.DateTimeField(null=True, verbose_name='End Datetime')),
            ],
            options={
                'ordering': ('-created_timestamp',),
                'abstract': False,
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
    ]
