# Generated by Django 3.0.3 on 2021-06-05 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=None, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=None, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Datetime'),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Datetime'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Title'),
        ),
    ]
