# Generated by Django 3.0.3 on 2021-06-05 20:25

import core.mixins.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210605_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=core.mixins.fields.S3CustomImageField(blank=True, max_length=1024, null=True, upload_to='articles'),
        ),
    ]
