# Generated by Django 3.0.3 on 2021-06-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='End Datetime'),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start Datetime'),
        ),
    ]
