# Generated by Django 3.0.2 on 2020-06-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yahooteam',
            name='multiyear_team',
        ),
        migrations.AddField(
            model_name='yahoomultileagueteam',
            name='teams',
            field=models.ManyToManyField(to='teams.YahooTeam', verbose_name='Teams'),
        ),
    ]
