# Generated by Django 3.0.2 on 2020-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooteam',
            name='waiver_priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Waiver Priority'),
        ),
    ]
