# Generated by Django 3.0.2 on 2020-06-29 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200629_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooTeamLeagueForecast',
            fields=[
                ('yahooteam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teams.YahooTeam')),
            ],
            options={
                'abstract': False,
            },
            bases=('teams.yahooteam', models.Model),
        ),
    ]
