# Generated by Django 3.0.2 on 2020-03-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_yahooteam_waiver_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahooteam',
            name='waiver_priority',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Waiver Priority'),
        ),
    ]
