# Generated by Django 3.0.2 on 2020-03-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200314_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooteam',
            name='manager_email',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Manager Email'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='manager_nickname',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Manager Nickname'),
        ),
    ]
