# Generated by Django 3.0.3 on 2020-07-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_yahooteamleagueforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahoomultileagueteam',
            name='nsvh',
            field=models.FloatField(blank=True, null=True, verbose_name='Net Saves or Holds'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='nsvh',
            field=models.FloatField(blank=True, null=True, verbose_name='Net Saves or Holds'),
        ),
    ]
