# Generated by Django 3.0.2 on 2020-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200314_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooteam',
            name='_def',
            field=models.FloatField(blank=True, null=True, verbose_name='Def'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='ab',
            field=models.FloatField(blank=True, null=True, verbose_name='At Bat'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='adp',
            field=models.FloatField(blank=True, null=True, verbose_name='WAR'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Average'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='bb',
            field=models.FloatField(blank=True, null=True, verbose_name='Base Balls'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='bb9',
            field=models.FloatField(blank=True, null=True, verbose_name='Base Balls in ( Inns'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='bba',
            field=models.FloatField(blank=True, null=True, verbose_name='Base Balls Allowed'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='bsr',
            field=models.FloatField(blank=True, null=True, verbose_name='BsR'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='cs',
            field=models.FloatField(blank=True, null=True, verbose_name='Caught Stolen'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='double',
            field=models.FloatField(blank=True, null=True, verbose_name='Doubles'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='er',
            field=models.FloatField(blank=True, null=True, verbose_name='Earned Run'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='era',
            field=models.FloatField(blank=True, null=True, verbose_name='Earned Run Average'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='fip',
            field=models.FloatField(blank=True, null=True, verbose_name='FIP'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='fld',
            field=models.FloatField(blank=True, null=True, verbose_name='Fld'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='g',
            field=models.FloatField(blank=True, null=True, verbose_name='Games'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='gs',
            field=models.FloatField(blank=True, null=True, verbose_name='Game Started'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='h',
            field=models.FloatField(blank=True, null=True, verbose_name='Hits'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Hits Allowed'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='hbp',
            field=models.FloatField(blank=True, null=True, verbose_name='Hit By Pitch'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='hr',
            field=models.FloatField(blank=True, null=True, verbose_name='Home Run'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='hra',
            field=models.FloatField(blank=True, null=True, verbose_name='Home Run Allowed'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='ip',
            field=models.FloatField(blank=True, null=True, verbose_name='Innings Pitched'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='k9',
            field=models.FloatField(blank=True, null=True, verbose_name='Strike Out in 9 Inns'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='l',
            field=models.FloatField(blank=True, null=True, verbose_name='Loses'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='obp',
            field=models.FloatField(blank=True, null=True, verbose_name='Obp'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='off',
            field=models.FloatField(blank=True, null=True, verbose_name='Off'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='ops',
            field=models.FloatField(blank=True, null=True, verbose_name='OPS'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='pa',
            field=models.FloatField(blank=True, null=True, verbose_name='Plate Appareances'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='r',
            field=models.FloatField(blank=True, null=True, verbose_name='Runs'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='rbi',
            field=models.FloatField(blank=True, null=True, verbose_name='Runs Bat in'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='sb',
            field=models.FloatField(blank=True, null=True, verbose_name='Stolen Base'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='slg',
            field=models.FloatField(blank=True, null=True, verbose_name='Slugging'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='so',
            field=models.FloatField(blank=True, null=True, verbose_name='Strike Out'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='soa',
            field=models.FloatField(blank=True, null=True, verbose_name='Strike Out Allowed'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='triple',
            field=models.FloatField(blank=True, null=True, verbose_name='Triples'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='w',
            field=models.FloatField(blank=True, null=True, verbose_name='Win'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='war',
            field=models.FloatField(blank=True, null=True, verbose_name='WAR'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='whip',
            field=models.FloatField(blank=True, null=True, verbose_name='WHIP'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='woba',
            field=models.FloatField(blank=True, null=True, verbose_name='wOBA'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='wrcplus',
            field=models.FloatField(blank=True, null=True, verbose_name='wRC+'),
        ),
    ]
