# Generated by Django 3.0.2 on 2020-03-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20200315_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooteam',
            name='h9',
            field=models.FloatField(blank=True, null=True, verbose_name='H/9'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='kbb',
            field=models.FloatField(blank=True, null=True, verbose_name='K/BB'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='nsb',
            field=models.FloatField(blank=True, null=True, verbose_name='Net Stolen Base'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='rapp',
            field=models.FloatField(blank=True, null=True, verbose_name='RAPP'),
        ),
    ]
