# Generated by Django 3.0.3 on 2020-07-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20200712_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahoomultileagueteam',
            name='teams',
            field=models.ManyToManyField(related_name='multi_league_teams', to='teams.YahooTeam', verbose_name='Teams'),
        ),
    ]
