# Generated by Django 3.0.2 on 2020-05-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20200315_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooteam',
            name='gap',
            field=models.FloatField(blank=True, null=True, verbose_name='Games as Pitcher'),
        ),
    ]
