# Generated by Django 3.0.3 on 2020-07-17 11:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_yahooteamleagueforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooteamleagueforecast',
            name='bat_stat_order',
            field=models.CharField(default='adp', max_length=512, verbose_name='Bat Stat Order'),
        ),
        migrations.AddField(
            model_name='yahooteamleagueforecast',
            name='is_regular_player_auto',
            field=models.BooleanField(default=True, verbose_name='Is auto'),
        ),
        migrations.AddField(
            model_name='yahooteamleagueforecast',
            name='pit_stat_order',
            field=models.CharField(default='adp', max_length=512, verbose_name='Bat Stat Order'),
        ),
        migrations.AddField(
            model_name='yahooteamleagueforecast',
            name='regular_player',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Regular Players'),
        ),
        migrations.AlterField(
            model_name='yahooteamleagueforecast',
            name='yahoo_team',
            field=models.ForeignKey(limit_choices_to={'league__is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_team', to='teams.YahooTeam', verbose_name='Yahoo Team'),
        ),
    ]
