# Generated by Django 3.0.3 on 2020-07-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_remove_yahooteamleagueforecast_bat_stat_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooteamleagueforecast',
            name='bat_stat_order',
            field=models.CharField(default='player__baseballavestats__adp', max_length=512, verbose_name='Bat Stat Order'),
        ),
        migrations.AlterField(
            model_name='yahooteamleagueforecast',
            name='pit_stat_order',
            field=models.CharField(default='player__baseballavestats__adp', max_length=512, verbose_name='Bat Stat Order'),
        ),
    ]
