# Generated by Django 3.0.3 on 2020-07-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20200717_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yahooteamleagueforecast',
            name='bat_stat_order',
        ),
        migrations.RemoveField(
            model_name='yahooteamleagueforecast',
            name='pit_stat_order',
        ),
    ]
