# Generated by Django 3.0.3 on 2020-07-19 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20200718_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahooteamleagueforecast',
            name='yahoo_team',
            field=models.OneToOneField(limit_choices_to={'league__is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_team', to='teams.YahooTeam', verbose_name='Yahoo Team'),
        ),
    ]
