# Generated by Django 3.0.3 on 2020-07-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20200719_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yahoomultileagueteam',
            name='l',
        ),
        migrations.RemoveField(
            model_name='yahoomultileagueteam',
            name='w',
        ),
        migrations.RemoveField(
            model_name='yahooteam',
            name='l',
        ),
        migrations.RemoveField(
            model_name='yahooteam',
            name='w',
        ),
        migrations.RemoveField(
            model_name='yahooteamleagueforecast',
            name='l',
        ),
        migrations.RemoveField(
            model_name='yahooteamleagueforecast',
            name='w',
        ),
        migrations.AddField(
            model_name='yahoomultileagueteam',
            name='so',
            field=models.FloatField(blank=True, null=True, verbose_name='Strike Out'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='so',
            field=models.FloatField(blank=True, null=True, verbose_name='Strike Out'),
        ),
        migrations.AddField(
            model_name='yahooteamleagueforecast',
            name='so',
            field=models.FloatField(blank=True, null=True, verbose_name='Strike Out'),
        ),
    ]
