# Generated by Django 3.0.3 on 2020-08-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20200725_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahoomultileagueteam',
            name='w_pct',
            field=models.FloatField(default=0, verbose_name='w_pct'),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='w_pct',
            field=models.FloatField(default=0, verbose_name='w_pct'),
        ),
        migrations.AddField(
            model_name='yahooteamleagueforecast',
            name='w_pct',
            field=models.FloatField(default=0, verbose_name='w_pct'),
        ),
    ]
